name: GITHUB_OUTPUT
on: push
jobs:
    share:
        runs-on: ubuntu-latest
        steps:
            - id: sourse
              run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
            - env:
                RESULT: ${{ steps.source.outputs.result }}
              run: echo "${RESULT}"